#################################### INSTALL SPECIFICATION LIST ####################################

############################## AI COMPONENTS ##############################

# TODO: Currently unused. Test in docker sandbox before using.
# [[list]]
# group = "ai"
# [list.meta]
# name = "aider"
# [list.installer]
# type = "run_script"
# url = "https://aider.chat/install.sh"
# cmd = "sh"

[[list]]
group = "ai"
[list.meta]
name = "opencode"
version = "1.2.20"
[list.installer]
type = "release_asset"
repo = "anomalyco/opencode"
tag = "v{version}"
asset = "{name}-linux-x64"
ext = ".tar.gz"
bin = "{name}"
# XXX: remove if above method works fine
# type = "run_script"
# url = "https://opencode.ai/install"
# cmd = "bash"
# args = "--no-modify-path --version {version}"
# bin = "{install_prefix}/bin/.opencode/bin/opencode"
# env = [["INSTALL_DIR", "{install_prefix}/bin"]]

############################## GIT COMPONENTS #############################

[[list]]
group = "git"
[list.meta]
name = "lazygit"
version = "0.54.2"
[list.installer]
type = "release_asset"
repo = "jesseduffield/lazygit"
tag = "v{version}"
asset = "{name}_{version}_linux_x86_64"
ext = ".tar.gz"
bin = "{name}"

[[list]]
group = "git"
[list.meta]
name = "delta"
version = "0.18.2"
[list.installer]
type = "release_asset"
repo = "dandavison/delta"
asset = "{name}-{version}-x86_64-unknown-linux-gnu"
ext = ".tar.gz"
bin = "{asset}/{name}"

# TODO: maybe AptLocal
# [[list]]
# group = "git"
# [list.meta]
# name = "git-crypt"
# version = "0.8.0"
# [list.installer]
# type = ""
# repo = "AGWA/git-crypt"
# asset = "git-crypt-{}-linux-x86_64"
# ext = ""

# TODO: add git-remote-gcrypt

############################ NEOVIM COMPONENTS ############################

# [[list]]
# group = "neovim"
# [list.meta]
# name = "neovim"
# version = "0.11.5"
# [list.installer]
# type = "build_source"
# repo = "neovim/neovim"
# commands = ["make -j8 CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$LOCAL_DIR", "make install"]

[[list]]
group = "neovim"
[list.meta]
name = "ripgrep"
version = "15.1.0"
[list.installer]
type = "release_asset"
repo = "BurntSushi/ripgrep"
asset = "{name}-{version}-x86_64-unknown-linux-musl"
ext = ".tar.gz"
bin = "{asset}/rg"

[[list]]
group = "neovim"
[list.meta]
name = "tree-sitter"
version = "0.26.6"
[list.installer]
type = "release_asset"
repo = "tree-sitter/tree-sitter"
tag = "v{version}"
asset = "{name}-linux-x64"
ext = ".gz"
bin = "{name}"

[[list]]
group = "neovim"
[list.meta]
name = "clangd"
version = "21.1.8"
[list.installer]
type = "release_asset"
repo = "clangd/clangd"
asset = "{name}-linux-{version}"
ext = ".zip"
pkg = true
bin = "{name}_{version}/bin/{name}"

[[list]]
group = "neovim"
[list.meta]
name = "lua-language-server"
version = "3.17.1"
[list.installer]
type = "release_asset"
repo = "LuaLS/lua-language-server"
asset = "{name}-{version}-linux-x64"
ext = ".tar.gz"
pkg = true
bin = "bin/{name}"

[[list]]
group = "neovim"
[list.meta]
name = "codelldb"
version = "1.12.1"
[list.installer]
type = "release_asset"
repo = "vadimcn/codelldb"
tag = "v{version}"
asset = "{name}-linux-x64"
ext = ".vsix"
pkg = true
bin = "extension/adapter/{name}"

[[list]]
group = "neovim"
[list.meta]
name = "debugpy"
version = "1.8.20"
[list.installer]
type = "python_venv"
pkg = "{name}"

############################ WEZTERM COMPONENTS ###########################
# TODO: implement this - wezterm
