name: 'Project: Handle Issues'
run-name: "Update Project - Issue #${{ github.event.issue.number }}"

on:
  issues:
    types: [closed]

permissions:
  issues: read

jobs:

  handle-close:
    name: Handle Closed Issues
    runs-on: ubuntu-latest
    steps:
      - name: Update Status to COMPLETED or DISCARDED
        uses: EndBug/project-fields@v2.1.0
        with:
          github_token: ${{ secrets.PROJECT_TOKEN }}
          project_url: ${{ vars.PROJECT_URL }}
          operation: set
          fields: Status
          values: ${{ github.event.issue.state_reason == 'completed' && 'COMPLETED' || 'DISCARDED' }}
