name: 'Project: Handle PRs'
run-name: "Update Project - PR #${{ github.event.pull_request.number }}"

on:
  pull_request:
    types: [opened, closed, reopened]

permissions:
  pull-requests: read

jobs:

  handle-open:
    name: Handle Opened PRs
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: Update Status to ONGOING
        uses: EndBug/project-fields@v2.1.0
        with:
          github_token: ${{ secrets.PROJECT_TOKEN }}
          project_url: ${{ vars.PROJECT_URL }}
          operation: set
          fields: Status
          values: ONGOING

  handle-close:
    name: Handle Closed PRs
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Update Status to COMPLETED or DISCARDED
        uses: EndBug/project-fields@v2.1.0
        with:
          github_token: ${{ secrets.PROJECT_TOKEN }}
          project_url: ${{ vars.PROJECT_URL }}
          operation: set
          fields: Status
          values: ${{ github.event.pull_request.merged == true && 'COMPLETED' || 'DISCARDED' }}
